name: Test Project
on: push

jobs:
  test:
    runs-on: ubunut-latest
    steps:
      - name : Get Code
        uses: actions/checkout@v4
      - name : Install NodeJS 
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependancies
        run: npm ci
      - name: Run Tests
        run: npm test
    # Runs a single command using the runners shell
    #   - name: Run a one-line script
    #     run: |
    #       echo "First Command"
    #       echo " Second Command"